version: '1'

services:
  api2:
    platform: linux/amd64
    command: bash -c "uvicorn api:app --host 0.0.0.0 --port 8001 --reload"
    build: .
    container_name: api2
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/var/app
      - /dev/snd:/dev/snd
      - shared_audio:/shared_audio


volumes:
  shared_audio:
    driver: local


